export default {
  login: {
    login: "Welcome to",
    title: "Welcome to",
    info: "ZOOMLION",
    username: "Please enter username.",
    password: "Please enter password.",
    wechat: "WeChat",
    qq: "QQ",
    phone: "Please enter phone number.",
    code: "Please enter verification code.",
    submit: "Login",
    userLogin: "Username & Password",
    phoneLogin: "Phone No. Login",
    thirdLogin: "Third Party Login",
    faceLogin: "Face Login",
    msgText: "Send Verification Code",
    msgSuccess: "Send Verification Code again after ** s",
    codelogin: "Login via QR code",
    openapp: "Open CRM APP",
    sanlogin: "Scan to log in",
    passlogin: "Password login",
    scanapp: "Scan QR Code to download APP",
    codescan: "Scan",
    confirmLogin: "Confirm login",
    crmconfitm: "CMR电脑端登录确认",
    securityhint: "To keep your account secure, make sure you're the person in charge.",
    codeText: "验证码"
  },
  tagsView: {
    tagsView: "Search",
    search: "Search",
    menu: "More",
    closeOthers: "Close Others",
    closeAll: "Close All Tabs",
    refresh: "Refresh",
    close: "Close"
  },
  error: {
    error: "Error",
    noRecorde: "Please select the data to be operated.",
    notUnique: "Only one piece of data can be selected for operation.",
    noStatus: "Please check the voucher status.",
    noSave: "Please fill in the required fields first.",
    noHead: "Please fill in the header information first.",
    noZhammSod: "Please add parts information.",
    noCompletedBoxing: "Packed",
    noboxed: "Unpacked",
    noCustSales: "Please select customer category.",
    noShippingSpaceInfo: "Please fill in the logistics booking information.",
    noPaymentCondition: "Please fill in the delivery conditions.",
    noZhammPakingItem2: "Materials exist in the secondary packing list for this carton number.",
    noPrdln: "Please select product line.",
    noKunnr: "Please select customer code.",
    noCurrency: "Please select currency.",
    noAmount: "Receivables should be greater than 0 and less than the remaining balance!",
    noRate: "Please enter the correct ratio.",
    noSelect: "Please select a piece of data!",
    noShipped: "The selected packing list is done.",
    noZhasd1: "Please add product information.",
    noZhasdSohp: "Please add detailed payment conditions.",
    noDocId: "Please save the header information first.",
    sodQTY: "Purchase QTY. is more than Order QTY.",
    needMaterial: "Please select material.",
    needSameMaterial: "Please select the same material.",
    receivingQTY: "Receiving QTY. should be less than or equal to the remaining QTY.",
    noColumn: "Please select a column"
  },
  notice: {
    notice: "Prompt",
    delete: "Confirm deletion?",
    add: "Confirm adding?",
    writeoff: "Confirm write-off?",
    print: "Confirm printing?",
    deploy: "Confirm deployment?",
    publish: "Confirm publishing?",
    loading: "Loading. Please wait…",
    saving: "Saving. Please wait…",
    submitting: "Submitting. Please wait…",
    loadErrorAndReload: "Network loading error. Reload?",
    confirmSave: "Confirm submission?",
    stop: "Confirm termination?",
    valid: "Valid",
    invalid: "Invalid",
    retransmission: "Confirm retransmission?",
    check: "The data cannot be modified after submission. Are you sure to check the next one?"
  },
  view: {
    view: "View",
    notice: "Prompt"
  },
  sysmenu: {
    sysmenu: "Menu",
    base: {
      base: "Basic Function",
      menu: "Menu Management",
      dictionary: "Dictionary Management",
      treeTemplate: "Tree Structure Management",
      catalog: "Classification Management",
      reference: "Reference Management",
      sequence: "Sequence Management",
      sysContext: "Context Management",
      importTemplate: "Import Management",
      exportTemplate: "Export Management",
      formTemplate: "Form Management",
      queryTemplate: "Query Management",
      domainTemplate: "Business model"
    }
  },
  global: {
    global: "Global",
    index: "Serial number",
    search: "Filters",
    selectFile: "Select File",
    upload: "Upload to Server",
    uploadSuccess: "Upload Succeeded",
    uploadFail: "Upload Failed",
    treeTemplate_download: "Download Template",
    file: "Attachment",
    appendix: "Attachment",
    uploaded: "Uploaded",
    need: "Please enter ",
    number: "Number",
    nonNegative: "Nonnegative Number",
    greaterThanZero: "Greater than 0",
    oneToTen: "1 to 10",
    enterKeywords: "Enter keywords to filter",
    button: {
      button: "Button",
      close: "Close",
      view: "View",
      search: "Search",
      clear: "Clear",
      empty: "Clear",
      add: "Add",
      deleteAll: "Delete All",
      edit: "Modify",
      takeOff: "Take Off",
      editPhone: "Change Phone No.",
      pointAdd: "Add Point",
      editAll: "Edit All",
      setAll: "Set All",
      delete: "Delete",
      cancel: "Close",
      ok: "OK",
      choose: "Select",
      operation: "Operate",
      reset: "Reset",
      save: "Save",
      submit: "Save And Submit",
      termination: "Terminate",
      mainTotal: "Total",
      subSave: "Save As Draft",
      divide: "Allocate",
      disabled: "Invalid",
      documentFlow: "Document Flow",
      availabilityCheck: "Availability Check",
      upload: "Upload",
      phoneLog: "Phone No. Change Log",
      nextStep: "Next Step",
      return: "Return",
      renewalPriceConfig: "Config Renewal Price",
      buyOnceTicket: "Once Ticket",
      buyPeriodTicket: "Period Ticket",
      buyCompanyTicket: "Company Ticket",
      buyExerciseTicket: "Exercise Ticket",
      renewal: "Renewal",
      privilege: "Privilege",
      agree: "Agree",
      disAgree: "Disagree",
      requisitionDetails: "Details",
      accountOrg: "Data Organization",
      accountRole: "User Role",
      wechat: "WeChat",
      alipay: "Alipay",
      config: "config",
      getDiscount: "Get Discount",
      import: "Import",
      export: "Export",
      batch: "Batch",
      createcustomer: "New Customer",
      sharerequest: "Customer Sharing",
      becomingapplication: "Customer Activation",
      createapplication: "Create Application Form",
      use: "Sharing",
      establish: "Create",
      createbusinessopportunities: "Create Pipeline",
      dailyvisit: "Daily Visit",
      Createdailyvisit: "Create Visit",
      custbecomeworker: "Customer Activation",
      publish: "Publish",
      globalPublish: "Global Publish",
      globalRecover: "Global Recover",
      immediateExecution: "Execute Now",
      addField: "Add",
      download: "Download",
      adjust: "Adjust",
      check: "Check",
      set: "Setting",
      remind: "Remind",
      clearCache: "Clear Cache",
      generate: "Generate",
      execute: "Transmit",
      runrecover: "Recall",
      distribute: "Allocate",
      relate: "Relate",
      convert: "Convert",
      CreateTrail: "New Lead",
      accept: "Accept",
      invalid: "Invalid",
      refuse: "Refuse",
      transfer: "Allocate",
      handover: "Cooperate",
      fullscreen: "FullScreen",
      outFullscreen: "Exit Full Screen",
      previousOne: "Previous",
      nextOne: "Next",
      skip: "Skip",
      person: "Person",
      unlock: "Unlock",
      open: "Open",
      shrink: "Shrink",
      chooseColumn: "Select a column",
      selectedColumn: "Selected column",
      selectedMenu: "Selected menu",
      copy: "Copy",
      authority: "Permission",
      user: "accountId",
      mobileUnbinding: "mobile Unbinding",
      importNewVersion: "import NewVersion",
      hstoricalVersion: "History Version",
      latestVersionQuery: "latest Version Query",
      executeImport: "ExecuteI mport",
      print: "Print",
      continueAdd: "continue Add",
      batchDownload: "Batch download",
      previousStrip: "previous Strip ",
      nextStrip: "Next",
      verificationLogId: "verification Log ",
      feishuSync: "飞书同步",
      summary: "Summary",
      userattribution: "User Attribution",
      dissolution: "解散",
      recovery: "恢复",
      teamModifiy: "团队修改",
      memberModifiy: "成员修改",
      permissionQuery: "权限查询",
      PersonnelOwnership: "人员归属",
      quit: "Quit",
      enableToggled: "启用/禁用",
      reference: "引用",
      widget: "控件",
      query: "查询",
      logData: "历史数据",
      release: "release",
      showAll: "显示全部",
      translatetext: "翻译文本"
    },
    submit: {
      submit: "Submit",
      success: "Operation Succeeded",
      saveSuccess: "Synchronization Succeeded"
    },
    dialog: {
      dialog: "Dialog",
      add: "Add",
      config: "config",
      edit: "Modify",
      reference: "引用",
      relate: "关联",
      queryConfig: "查询配置",
      editPhone: "Change Phone No.",
      notice: "Prompt",
      view: "View",
      posting: "Posting",
      isAccount: "Account Recording",
      writeoff: "Write-off",
      choose: "Select",
      import: "Data Import",
      setting: "Setting",
      authority: "Permission",
      isrole: "Role",
      changepassword: "Change Password",
      replacementupdate: "Commodity Invoice",
      costupdate: "Expense Invoice",
      replacementsubmit: "Invoice Submission",
      costsubmit: "Invoice Submission",
      summary: "Summary",
      ok: "OK",
      cancel: "Cancel",
      cancellationreason: "Please enter the reason for invalidation.",
      renewalPriceConfig: "Please enter renewal price.",
      requisitionDetails: "Details",
      validateMemberInfo: "Validate Member Info",
      docInfo: "Document Info",
      adjust: "Adjust",
      check: "Check",
      distribute: "Allocate",
      copy: "Copy",
      more: "More",
      retract: "retract",
      annualBudgetPublish: "Annual Budget Publish",
      monthlyBudgetPublish: "Monthly Budget Publish",
      monthlyBudgetImportProcess: "Monthly Budget Import Process",
      reimbursementExpenseDetails: "Details",
      integratedInformation: "Comprehensive information",
      loanInfo: "Loan Information",
      verificationLogDetail: "verification LogDetail",
      otherExpenseReimburseApply: "Other Expense Reimburse Apply ",
      ApprovalInfo: "Approval Information",
      approvalInfo: "Approval Information",
      centrExpenseReimburseApply: "Centralized reimbursement apply",
      travelExpenseReimburseApply: "Travel Reimbursement Apply",
      repaymentInformation: "Repayment Information",
      loanInformation: "Loan Information",
      repaymentApplication: "Repayment Application",
      repaymentRecordsDetails: "Repayment record details",
      teamMembers: "团队成员",
      permissionDisplay: "权限显示",
      loanApplication: "Loan Application",
      applicableObject: "适用对象",
      progressTracking: "进度跟踪",
      competitiveSituation: "竞争态势"
    },
    error: {
      error: "Error",
      netError: "The network is busy. Please try again later.",
      noRecorde: "Please select the data to be operated.",
      notUnique: "Only one piece of data can be selected for operation.",
      noStatus: "Please check the voucher status.",
      noSave: "Please fill in the required fields first.",
      noHead: "Please fill in the header information first.",
      noZhammSod: "Please add parts information.",
      noCompletedBoxing: "Packed",
      noboxed: "Unpacked",
      noCustSales: "Please select customer category.",
      noShippingSpaceInfo: "Please fill in the logistics booking information.",
      noPaymentCondition: "Please fill in the delivery conditions.",
      noZhammPakingItem2: "Materials exist in the secondary packing list for this carton number.",
      noPrdln: "Please select product line.",
      noKunnr: "Please select customer code.",
      noCurrency: "Please select currency.",
      noAmount: "Receivables should be greater than 0 and less than the remaining balance!",
      noRate: "Please enter the correct ratio.",
      noSelect: "Please select a piece of data!",
      noShipped: "The selected packing list is done.",
      noZhasd1: "Please add product information.",
      noZhasdSohp: "Please add detailed payment conditions.",
      sodQTY: "Purchase QTY. is more than Order QTY.",
      needMaterial: "Please select material.",
      needSameMaterial: "Please select the same material.",
      receivingQTY: "Receiving QTY. should be less than or equal to the remaining QTY.",
      required: "Please check the required fields (*).",
      noOneIsEligible: "No one is eligible.",
      noMatchRecord: "No Matched Record",
      noNeedRenewal: "No Need for Renewal",
      unknownError: "Unknown Error",
      netConnectError: "Network Connection Error",
      selectTrailcheck: "Please select at least one lead to check.",
      NormtcodeExists: "Product model already exists",
      passwordExpired: "您的密码将于 {0} 天后过期，请尽快修改密码！"
    },
    notice: {
      notice: "Notice",
      delete: "Confirm deletion?",
      runrecover: "Confirm recovery?",
      publish: "Confirm publishing?",
      add: "Confirm adding?",
      writeoff: "Confirm write-off?",
      print: "Confirm printing?",
      deploy: "Confirm deployment?",
      loading: "Loading. Please wait…",
      saving: "Saving. Please wait…",
      submitting: "Submitting. Please wait…",
      loadErrorAndReload: "Network loading error. Reload?",
      confirmSave: "Confirm submission?",
      stop: "Confirm termination?",
      valid: "Valid",
      invalid: "Invalid",
      retransmission: "Confirm retransmission?",
      refreshSys: "The system version is updated. Click confirm to load the latest version or press Ctrl+F5.",
      confirmStartCheck: "Confirm to start check?",
      refuse: "Are you sure to reject?",
      validatePassedAndSubmit: "Validate Passed And Submit",
      validateFailedAndViewDetail: "Validate Failed And View Detail",
      quit: "确定退出吗?",
      enableToggled: "确定切换所有选中项的【启用/禁用】状态?",
      toggledDone: "切换完成！",
      cancelled: "已取消！"
    },
    view: {
      view: "View",
      notice: "Prompt"
    },
    page: {
      page: "Close Current Tab",
      closeCurrent: "Close Current Tab",
      closeOther: "Close Other Tabs",
      closeAll: "Close All Tabs",
      reload: "Reload Current Tab",
      cantfindpage: "No available tabs are found.",
      exit: "Log out the system?",
      yes: "Yes",
      no: "No",
      loading: "Loading",
      oldPwd: "Old Password",
      newPwd: "New password",
      confirmPwd: "Confirm Password",
      confirmPwdError: "Confirm Password is inconsistent with New Password.",
      oldPwdnull: "Old Password cannot be empty.",
      newPwdNull: "New Password cannot be empty.",
      confirmPwdNull: "Confirm Password cannot be empty."
    },
    uploadTable: {
      uploadTable: "Upload Table",
      name: "File Name",
      uploadPerson: "Uploader",
      uploadDate: "Upload Date",
      path: "File Path",
      uploadTime: "upload time"
    },
    systemDate: "System date",
    noData: "No Data",
    subtotal: "Subtotal of functional currency ",
    totalAmount: "Total amount ",
    languageSwitching: "Language switching"
  },
  title: "ZOOMLION",
  logoutTip: "Exit the system. Do you want to continue?",
  submitText: "Confirm",
  cancelText: "Cancel",
  search: "Please input search content.",
  menuTip: "No menu is found.",
  feedback: "Feedback",
  submit: "Submit",
  globel: {
    globel: "Global",
    common: {
      common: "Global",
      getCode: "Failed to get dictionary.",
      insertFail: "Failed to insert data synchronously."
    }
  },
  access_denied: "The account is locked, please contact the administrator!",
  access_verification_code_error: "Verification code error!",
  access_account_pwd_error: "Username or password error!"
};
